### PR TITLE
Added nano and shutdown

### PR DESCRIPTION
**Pull request by DSigmund**
Some Additions :-)

### CODE REVIEW

**Comment by ayust** [comment]
Hm. The shutdown one doesn't seem quite so "underhanded" as just spiteful; and it doesn't feel clever. (Granted, there are a couple of existing ones that aren't super clever, but I don't really want to add more.)

**Comment by DSigmund** [comment]
Yeah, youre right about that...
But i thought of a new one:
`alias ll=ls` #Who needs these infos anyway?

**Comment by ghost** [comment]
How about aliasing nano to vim or emacs instead?

**Comment by ayust** [comment]
vim or emacs both already are aliased to other things, so it's probably best not to chain aliases.

**Pull request closed without merging**
